# SPDX-FileCopyrightText: Copyright (c) 2025 - 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=10000]
        exclude: |
          (?x)^(
              frontend/package-lock.json |
              .licenses/details.json |
          )$
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: .gitlab-ci.yml
      - id: debug-statements

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        exclude: ^(setup.py|test/|.ci/)
        args: [--config=pyproject.toml]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        exclude: |
          (?x)^(.licenses |
          .ci |
          nim)
        args: [--disable=MD024]

  - repo: local
    hooks:
      - id: license
        name: license
        entry: python test/_license/header_check.py
        language: python
        files: \.(py|yaml|ci|release)$|Dockerfile$
        exclude: ^(docs/)
