#!/usr/bin/env bash
set -euo pipefail

# Run from the project root (or pass an absolute output path).  This records
# the exact package set of the selected environment; it does not include
# source code from packages/framework or packages/ops, which are exposed via
# PYTHONPATH by activate_hygon_env.sh.
mode="${1:-project}"
output="${2:-configs/hygon-reference-lock.txt}"
script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(CDPATH= cd -- "$script_dir/.." && pwd)"

# shellcheck source=/dev/null
source "$project_root/scripts/activate_hygon_env.sh" "$mode"

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT
UV_CACHE_DIR="${UV_CACHE_DIR:-/data/envs/uv-cache}" \
  uv pip freeze --python "$HYGON_PYTHON_ENV/bin/python" | sort > "$tmp_file"

{
  printf '%s\n' '# Exact freeze generated by scripts/freeze_hygon_env.sh.'
  printf '%s\n' '# Environment: project .venv; Python/Torch wheels are host-local inputs.'
  printf '%s\n' '# Recreate: source scripts/activate_hygon_env.sh project && uv pip sync --python .venv/bin/python --index-url https://mirrors.bfsu.edu.cn/pypi/web/simple configs/hygon-reference-lock.txt'
  cat "$tmp_file"
} > "$project_root/$output"
printf 'wrote %s\n' "$project_root/$output"
